### ISSUE TITLE
no module named app alembic migraiton issue

### ISSUE THREAD

**Issue by GomesNayagam** [ThomasAitken/demo-fastapi-async-sqlalchemy#1]
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/gsubramanian/dev/workbook-api/app/alembic/env.py", line 9, in <module>
    from app.config import settings
ModuleNotFoundError: No module named 'app'

**Comment by ThomasAitken** [comment]
Not sure exactly what you did to get to this point but in response to your issue I've made some corrections to make it easier to get this repo up and running. Like I say in the README, this repo is designed to be a simplified example, rather than a working prototype but fair enough to raise this.

Once you pull the latest commit, you should be able to start the project by simply invoking `docker compose up -d`. If you want to make a change to a model then create a migration file, I recommend doing so using the existing command i.e. `backend/scripts/autogenerate_migrations.sh "your migration message"`. You should be able to run this migration using `backend/scripts/run_migrations.sh`. Let me know if this resolves your issue.

**Comment by GomesNayagam** [comment]
i mean without docker compose when i run alembic revison command it is not able to resolve the module,later i found and added sys.path to make it work. thanks anyway for the work, it is useful.
